layout_spectrum: 0.9192741
name: Jessie Radies
title: make a difference
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.5012516
  lightness: 0.42310376977548
  saturation: 0.6398062105290592
  rhythmicContrast: 0.7288948609493673
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.3973717
