name: make a difference
favicon: null
layout_spectrum: 0.6662
typography_spectrum: 0.5550689
title: make a difference
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-79205826-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.198373
  lightness: 0.5625
  saturation: 0.8854818
  rhythmicContrast: 0.6376721
purpose: []
