name: make a difference
favicon: null
layout_spectrum: 0.6662
typography_spectrum: 0.22912
title: Jessie Radies
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-79205826-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfdfb'
    - '#2e3b0c'
    - '#337acc'
    - '#d8a288'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
