color:
  brandStrength: 0.198373
  saturation: 0.8854818
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.5625
  rhythmicContrast: 0.6376721
title: make a difference
analytics:
  twitter: null
  google: null
  facebook: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.6662
purpose: []
name: make a difference
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5550689
