layout_spectrum: 0.887985
name: Jessie Radies
title: make a difference
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.5550689
color:
  brandStrength: 0.198373
  lightness: 0.8266583
  saturation: 0.8854818
  rhythmicContrast: 0.6376721
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
